export const UPVOTED_POSTS = 'UPVOTED_POSTS';
export const DOWNVOTED_POSTS = 'DOWNVOTED_POSTS';
export const UPDATE_TIMELINE = 'UPDATE_TIMELINE';
export const REDUCE_TIMELINE = 'REDUCE_TIMELINE';
export const SET_FILTER = 'SET_FILTER';
export const UPDATE_USER = 'UPDATE_USER';